"""add_recurring_type_to_recurring_transactions

Revision ID: 6ed555ae38df
Revises: 9db8ffa07d18
Create Date: 2025-07-26 12:47:49.065205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed555ae38df'
down_revision = '9db8ffa07d18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    recurring_type_enum = sa.Enum('AUTOMATIC', 'REMINDER', name='recurringtype')
    recurring_type_enum.create(op.get_bind())
    
    # Add the column as nullable
    op.add_column('recurring_transactions', sa.Column('recurring_type', recurring_type_enum, nullable=True))
    
    # Set default value for existing records
    op.execute("UPDATE recurring_transactions SET recurring_type = 'AUTOMATIC' WHERE recurring_type IS NULL")
    
    # Make the column non-nullable
    op.alter_column('recurring_transactions', 'recurring_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_transactions', 'recurring_type')
    # Drop the enum type
    sa.Enum(name='recurringtype').drop(op.get_bind())
    # ### end Alembic commands ###