"""add_cascade_deletion_constraints

Revision ID: 9db8ffa07d18
Revises: b2cb4a921abe
Create Date: 2025-07-19 17:39:18.260294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db8ffa07d18'
down_revision = 'b2cb4a921abe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recurring_transactions_user_id_fkey', 'recurring_transactions', type_='foreignkey')
    op.drop_constraint('recurring_transactions_budget_id_fkey', 'recurring_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'recurring_transactions', 'budgets', ['budget_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recurring_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('transaction_subcategories_category_id_fkey', 'transaction_subcategories', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_subcategories', 'transaction_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('transactions_budget_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_user_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'budgets', ['budget_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_budgets_budget_id_fkey', 'user_budgets', type_='foreignkey')
    op.drop_constraint('user_budgets_user_id_fkey', 'user_budgets', type_='foreignkey')
    op.create_foreign_key(None, 'user_budgets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_budgets', 'budgets', ['budget_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_budgets', type_='foreignkey')
    op.drop_constraint(None, 'user_budgets', type_='foreignkey')
    op.create_foreign_key('user_budgets_user_id_fkey', 'user_budgets', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_budgets_budget_id_fkey', 'user_budgets', 'budgets', ['budget_id'], ['id'])
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_user_id_fkey', 'transactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('transactions_budget_id_fkey', 'transactions', 'budgets', ['budget_id'], ['id'])
    op.drop_constraint(None, 'transaction_subcategories', type_='foreignkey')
    op.create_foreign_key('transaction_subcategories_category_id_fkey', 'transaction_subcategories', 'transaction_categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'recurring_transactions', type_='foreignkey')
    op.drop_constraint(None, 'recurring_transactions', type_='foreignkey')
    op.create_foreign_key('recurring_transactions_budget_id_fkey', 'recurring_transactions', 'budgets', ['budget_id'], ['id'])
    op.create_foreign_key('recurring_transactions_user_id_fkey', 'recurring_transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###